default:
  tags:
    - high-speed-runner

stages:
  - lint
  - prepare
  - build

include:
  - component: $CI_SERVER_FQDN/jek-dev/devops/components/maven/maven-syntax-check@0.1.0
    inputs:
      working_dir: "$CI_PROJECT_DIR/backend"
  - component: $CI_SERVER_FQDN/jek-dev/devops/components/maven/maven-pull-dependencies@0.1.0
    inputs:
      job_stage: "prepare"
      job_needs:
        - job: Maven:Syntax-Check
      working_dir: "$CI_PROJECT_DIR/backend"
  - component: $CI_SERVER_FQDN/jek-dev/devops/components/maven/maven-build@0.1.0
    inputs:
      working_dir: "$CI_PROJECT_DIR/backend"
      artefact_expire: "7 days"
      job_needs:
        - job: Maven:Pull-Dependencies
      artefact_path:
        - $CI_PROJECT_DIR/backend/target/*.jar
      maven_options: "package -DskipTests"
      
