spring.application.name=apidoc
spring.banner.location=classpath:banner.txt
spring.jpa.open-in-view=false
# The database name should be known to build the database url
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}